### ISSUE TITLE
Error due to block insertion via Side Menu - Slash Menu open in a block that doesn't contain inline content

### ISSUE THREAD

**Issue by marsee339** [TypeCellOS/BlockNote#404] opened 2023-10-31 11:31 UTC
**Bug**

![image](https://github.com/TypeCellOS/BlockNote/assets/57190250/ab03b40b-1228-4421-b8b6-440b59ea29d2)

**To Reproduce**
1. Add a custom block without InlineContent
2. Click the + in its Side Menu and select the default text block (e,g, Heading). 
The editor crashes with the error - **Slash Menu open in a block that doesn't contain inline content.**

Reproduced in https://www.blocknotejs.org/examples/alert-block (if you remove InlineContent in it).
Other custom blocks are added under the current block without problems

**Comment by matthewlipski** [comment] 2023-11-01 13:59
Hmm I'm seeing a different bug, the slash menu opens fine but a new block below isn't created - did you both remove the `InlineContent` component from `render`, and change `containsInlineContent` to `false`?

**Comment by marsee339** [comment] 2023-11-01 15:49
Here is the full code for Alert.tsx https://www.blocknotejs.org/examples/alert-block
It's still reproducing
![image](https://github.com/TypeCellOS/BlockNote/assets/57190250/f3bdfa64-3e56-4a7a-b96f-6de61375fe58)

Just slightly correct the condition in 
const blockIsEmpty = block.content!.length === 0;
to
const blockIsEmpty = block.content && block.content!.length === 0;

`import {
  BlockNoteEditor,
  BlockSpec,
  DefaultBlockSchema,
  defaultProps,
  PropSchema,
  SpecificBlock,
} from "@blocknote/core";
import {
  createReactBlockSpec,
  InlineContent,
  ReactSlashMenuItem,
} from "@blocknote/react";
import { RiAlertFill } from "react-icons/ri";
import { MdCancel, MdCheckCircle, MdError, MdInfo } from "react-icons/md";
import { Menu } from "@mantine/core";

// The types of alerts that users can choose from
export const alertTypes = {
  warning: {
    icon: MdError,
    color: "#e69819",
    backgroundColor: {
      light: "#fff6e6",
      dark: "#805d20",
    },
  },
  error: {
    icon: MdCancel,
    color: "#d80d0d",
    backgroundColor: {
      light: "#ffe6e6",
      dark: "#802020",
    },
  },
  info: {
    icon: MdInfo,
    color: "#507aff",
    backgroundColor: {
      light: "#e6ebff",
      dark: "#203380",
    },
  },
  success: {
    icon: MdCheckCircle,
    color: "#0bc10b",
    backgroundColor: {
      light: "#e6ffe6",
      dark: "#208020",
    },
  },
} as const;

// The props for the Alert block
export const alertPropSchema = {
  textAlignment: defaultProps.textAlignment,
  textColor: defaultProps.textColor,
  type: {
    default: "warning" as const,
    values: ["warning", "error", "info", "success"] as const,
  },
} satisfies PropSchema;

// Component for the Alert block
export const Alert = (props: {
  block: SpecificBlock<
    DefaultBlockSchema & {
    alert: BlockSpec<"alert", typeof alertPropSchema, true>;
  },
    "alert"
  >;
  editor: BlockNoteEditor<
    DefaultBlockSchema & {
    alert: BlockSpec<"alert", typeof alertPropSchema, true>;
  }
  >;
  theme: "light" | "dark";
}) => {
  const Icon = alertTypes[props.block.props.type].icon;

  return (
    <div
      className={"alert"}
      style={{
        ...alertStyles,
        backgroundColor:
          alertTypes[props.block.props.type].backgroundColor[props.theme],
      }}>
      {/*Icon which opens a menu to choose the Alert type*/}
      <Menu zIndex={99999}>
        <Menu.Target>
          {/*Icon wrapper to change the color*/}
          <div
            className={"alert-icon-wrapper"}
            style={{
              ...alertIconWrapperStyles,
              backgroundColor: alertTypes[props.block.props.type].color,
            }}
            contentEditable={false}>
            {/*Icon itself*/}
            <Icon
              className={"alert-icon"}
              style={{
                color:
                  alertTypes[props.block.props.type].backgroundColor[
                    props.theme
                  ],
              }}
              size={32}
            />
          </div>
        </Menu.Target>
        {/*Dropdown to change the Alert type*/}
        <Menu.Dropdown>
          <Menu.Label>Alert Type</Menu.Label>
          <Menu.Divider />
          {Object.entries(alertTypes).map(([key, value]) => {
            const ItemIcon = value.icon;
            
            return (
              <Menu.Item
                key={key}
                icon={<ItemIcon color={value.color} />}
                onClick={() =>
                  props.editor.updateBlock(props.block, {
                    type: "alert",
                    props: { type: key as keyof typeof alertTypes },
                  })
                }>
                {key.slice(0, 1).toUpperCase() + key.slice(1)}
              </Menu.Item>
            );
          })}
        </Menu.Dropdown>
      </Menu>
      {/*Rich text field for user to type in*/}
    </div>
  );
};

// Function which creates the Alert block itself, where the component is styled
// correctly with the light & dark theme
export const createAlertBlock = (theme: "light" | "dark") =>
  createReactBlockSpec<
    "alert",
    typeof alertPropSchema,
    true,
    DefaultBlockSchema & {
      alert: BlockSpec<"alert", typeof alertPropSchema, true>;
    }
  >({
    type: "alert" as const,
    propSchema: {
      textAlignment: defaultProps.textAlignment,
      textColor: defaultProps.textColor,
      type: {
        default: "warning",
        values: ["warning", "error", "info", "success"],
      },
    } as const,
    containsInlineContent: false,
    render: (props) => <Alert {...props} theme={theme} />,
  });

// Slash menu item to insert an Alert block
export const insertAlert = {
  name: "Alert",
  execute: (editor) => {
    const block = editor.getTextCursorPosition().block;
    const blockIsEmpty = block.content && block.content!.length === 0;

    // Updates current block to an Alert if it's empty, otherwise inserts a new
    // one below
    if (blockIsEmpty) {
      editor.updateBlock(block, { type: "alert" });
    } else {
      editor.insertBlocks(
        [
          {
            type: "alert",
          },
        ],
        editor.getTextCursorPosition().block,
        "after"
      );
      editor.setTextCursorPosition(editor.getTextCursorPosition().nextBlock!);
    }
  },
  aliases: [
    "alert",
    "notification",
    "emphasize",
    "warning",
    "error",
    "info",
    "success",
  ],
  group: "Other",
  icon: <RiAlertFill />,
  hint: "Used to emphasize text",
} satisfies ReactSlashMenuItem<
  DefaultBlockSchema & {
    alert: BlockSpec<"alert", typeof alertPropSchema, true>;
  }
>;

const alertStyles = {
  display: "flex",
  justifyContent: "center",
  alignItems: "center",
  flexGrow: 1,
  borderRadius: "4px",
  height: "48px",
  padding: "4px",
} as const;

const alertIconWrapperStyles = {
  borderRadius: "16px",
  display: "flex",
  justifyContent: "center",
  alignItems: "center",
  marginLeft: "12px",
  marginRight: "12px",
  height: "18px",
  width: "18px",
  userSelect: "none",
  cursor: "pointer",
} as const;

const inlineContentStyles = {
  flexGrow: "1",
};`

**Comment by matthewlipski** [comment] 2023-11-05 17:48
Ah yeah, I see the issue now. The bug actually goes deeper - for some reason the text cursor position doesn't update internally when the slash menu opens, only after you start typing. Thanks for reporting this, will fix👍

**Comment by nicholasdavidbrown** [comment] 2024-02-27 04:19
> Ah yeah, I see the issue now. The bug actually goes deeper - for some reason the text cursor position doesn't update internally when the slash menu opens, only after you start typing. Thanks for reporting this, will fix👍

Would this also cause the behaviour of having your cursor active in a block above, and then if you scroll to add a block somewhere else the slash menu tries to scroll back to where your cursor was last active?

**Comment by matthewlipski** [comment] 2024-05-31 18:34
Seems like both of these issues are fixed now, can't reproduce them on 0.13.4 - gonna close this issue

**Closed by matthewlipski** 2024-05-31 18:34 UTC
Labels: bug, prio:high
