### ISSUE TITLE
Initializing editor with content that has custom blocks results in error

### ISSUE THREAD

**Issue by handzlikt** [TypeCellOS/BlockNote#345] opened 2023-09-21 12:17 UTC
**Describe the bug**

After adding the save and load functionality (https://www.blocknotejs.org/examples/saving-loading) to the Alert Block example (https://www.blocknotejs.org/examples/alert-block)
the editor throws an error on initialization whenever the Alert Block is present in the content.
Same happens with the much simple example of Custom Blocs usage https://www.blocknotejs.org/docs/block-types#custom-block-types

**To Reproduce**

1. Visit https://codesandbox.io/s/epic-forest-c5zwzz
2. Enter some content that is different than the Alert element
3. Refresh the browser inside sandbox -> the editor should initialize with the previous content
4. Add Alert element
5. Refresh the browser inside sandbox -> the editor raises 'RangeError: Position undefined out of range'

**Misc**
- Package manager: npm
- Browser: Chrome

**Comment by marwan37** [comment] 2023-09-24 23:52
I don’t have a definitive solution for the issue you’re encountering, but I’d like to share some insights that might help.

In my project, I’ve been using Yjs with IndexedDb to store the editor's content and haven’t encountered the `RangeError` you mentioned. I suspected the issue might be related to `localStorage`, so I attempted to reproduce the CodeSandbox environment locally, using your `Alert.tsx` code . I stored the content in `localStorage` and initialized it from there, but still didn’t experience any issues. Same for other custom block types like `Image`.

Out of curiosity, are you seeing the `RangeError` in your local environment as well, or only in the code sandbox? It’s possible that the issue could be related to the sandbox environment itself.

**Comment by todthomson** [comment] 2023-09-25 01:20
I think this error is the same that this PR fixes:
https://github.com/TypeCellOS/BlockNote/pull/336

**Comment by handzlikt** [comment] 2023-09-25 09:40
It's not only an sandbox issue - I get in  my local env as well. It happens also when the initial content is hardcode instead of read from `localStorage`. What's interesting it doesn't occur in the production build of the app.

@todthomson thank you, it looks indeed as a potential duplicate of [https://github.com/TypeCellOS/BlockNote/pull/336](#336)

**Comment by matthewlipski** [comment] 2023-09-27 13:25
Ok I found the root cause of the issue, tl;dr the initial content is rendered before the underlying TipTap editor is fully initialized, which doesn't affect default blocks (they don't use any editor functions when rendering) but throws an error for custom blocks. Should be fixed in #348👍

**Closed** 2023-10-04 16:35 UTC
Labels: bug
