### ISSUE TITLE
(NextJS on M1 OSX) TypeError: Cannot read properties of null (reading 'nearestDes')

### ISSUE THREAD

**Issue by ishan-flek-ai** [TypeCellOS/BlockNote#133] opened 2023-03-15 07:36 UTC
Running Next13 on M1 OSX with SSR disabled. Cannot reproduce when this happens exactly. But I get this error at times.
<img width="960" alt="Screenshot 2023-03-15 at 1 05 15 PM" src="https://user-images.githubusercontent.com/121634141/225238678-1a9a50f8-10d3-4fee-aa4e-b665338b4707.png">

**Comment by ishan-flek-ai** [comment] 2023-03-15 07:51
Tried it on a brand new next app using create-next-app and was able to reproduce this error. Tried main repo and running the example and I am not getting the error. In the next app I have also disabled ssr on the page this is loading using dynamic still getting this error.

So looks like next specific error.

**Comment by mkarbo** [comment] 2023-03-15 13:22
#123 might be the same :)

**Comment by ishan-flek-ai** [comment] 2023-03-15 19:38
@YousefED Hey is there a debugger configuration to attach the debugger in vscode. And if you have 15 mins sometime could you give me a code walkthrough? I am really interested in contributing to this repository. I find it incredible how close to notion this looks. :D

**Comment by YousefED** [comment] 2023-03-20 11:22
Closing this as it's a duplicate of https://github.com/TypeCellOS/BlockNote/issues/123 (which has been fixed).

@ishan-flek-ai contributions are super welcome! Feel free to reach out on Discord!

**Closed by YousefED** 2023-03-20 11:22 UTC

**Comment by YousefED** [comment] 2023-03-31 12:21
Fyi, nextjs should work more straightforward as part of v0.5.1: https://github.com/TypeCellOS/BlockNote/releases/tag/v0.5.1. `dynamic` is no longer needed
