### ISSUE TITLE
Ability to drag blocks next to each other to create columns 

### ISSUE THREAD

**Issue by shahyan3** [TypeCellOS/BlockNote#674] opened 2024-03-31 14:03 UTC
At the moment blocks can be dragged to the top or down. It'd be great to be able to drag blocks next to each other to create columns (left/right)

**Comment by YousefED** [comment] 2024-04-08 08:20
duplicate of https://github.com/TypeCellOS/BlockNote/issues/350

**Closed by YousefED** 2024-04-08 08:20 UTC
Labels: enhancement
