### ISSUE TITLE
How to create a custom codeblock function with tiptap in blocknote?

### ISSUE THREAD

**Issue by JIAN11442** [TypeCellOS/BlockNote#687] opened 2024-04-04 03:23 UTC
Based on the official custom alert block example,

https://www.blocknotejs.org/docs/custom-schemas/custom-blocks

 I'd like to customize a codeblock feature.

**Comment by YousefED** [comment] 2024-04-08 08:14
duplicate of https://github.com/TypeCellOS/BlockNote/issues/147

**Closed by YousefED** 2024-04-08 08:14 UTC
Labels: enhancement
