### ISSUE TITLE
Bug: Bubble menu placement not updating correctly

### ISSUE THREAD

**Issue by matthewlipski** [TypeCellOS/BlockNote#79] opened 2023-01-11 17:43 UTC
When setting the block type using the bubble menu, e.g. from a paragraph to a heading, the new bubble menu position is not updated correctly due to the animation. This is because the bounding box for the editor's selection is computed when the user clicks the paragraph/heading/list item button, meaning it's computed at the start of the animation. As the block is visually still of the old type at this point, the bounding box doesn't change. Only after the user reselects the text does the bounding box get updated to the correct values.

Example:

User selects Heading 1:
![image](https://user-images.githubusercontent.com/50169049/211878191-f4346ced-f6fc-4b8c-a884-2508a103827e.png)
Bubble menu position doesn't change:
![image](https://user-images.githubusercontent.com/50169049/211878285-18c6bf2e-ff75-4734-836e-91a9b31d61de.png)
Bubble menu position updates correctly only after user reselects the text:
![image](https://user-images.githubusercontent.com/50169049/211878704-8fb576ac-aec6-4ba5-8804-c1385f59493b.png)

This was previously somewhat fixed by delaying updating the bubble menu until the animation completes, but this was not a robust solution as it caused unnecessary delays when setting font styles and sometimes caused the menu to attempt to update when it was hidden.

**Comment by YousefED** [comment] 2023-05-30 12:25
I couldn't reproduce this anymore, and it also seems quite minor. Closing

**Closed by YousefED** 2023-05-30 12:25 UTC
Labels: bug
