### ISSUE TITLE
Space Disappears in Custom Block with Inline Content(Firefox)

### ISSUE THREAD

**Issue by hsingh-ds** [TypeCellOS/BlockNote#705] opened 2024-04-16 20:38 UTC
**Describe the bug**
When you try to add a space within a custom block with inline content on firefox, the space disappears, and any text added after the space gets concatenated without it. This is working in Chrome.

**To Reproduce**
Here is the [link](https://www.blocknotejs.org/docs/custom-schemas/custom-blocks) of the example that is given on the blocknote website

**Comment by YousefED** [comment] 2024-05-01 11:33
I think this is a duplicate of https://github.com/TypeCellOS/BlockNote/issues/659

**Closed by YousefED** 2024-05-01 11:33 UTC
Labels: bug
