### ISSUE TITLE
Firefox: Trailing Whitespace Removed in Custom Blocks

### ISSUE THREAD

**Issue by luukbox** [TypeCellOS/BlockNote#1015] opened 2024-08-19 12:09 UTC
**Describe the bug**
In Firefox, the last trailing whitespace in custom blocks is removed when typing a non-whitespace character. The issue only affects the end of the text, where only one space can be entered. Additional spaces are truncated and typing any character deletes the last space. This problem doesn't occur in Chrome or Safari.

**To Reproduce**
1. Open Firefox and visit the [docs](https://www.blocknotejs.org/docs/custom-schemas/custom-blocks#custom-block-types).
1. Enter one or more spaces followed by any character at the end of text in the alert block.

**Misc**
- Browser: Firefox 129.0.1 on Windows 11

Please see the attached GIF demonstrating the issue:
![ezgif-3-0e2112b0b5](https://github.com/user-attachments/assets/72654242-4651-44be-8dff-0403602b876c)

**Comment by YousefED** [comment] 2024-08-24 09:45
Hi Luuk,

I think this is a duplicate of https://github.com/TypeCellOS/BlockNote/issues/659, correct?

What are you building with BlockNote btw? Always curious :)

**Closed by YousefED** 2024-08-24 09:45 UTC
Labels: bug

**Comment by luukbox** [comment] 2024-08-26 07:19
Hi Yousef,

you are absolutely right, I must have missed that.

The editor will be part of an internal CMS. At the moment we are still testing the implementation but we are already excited about how easy it is to extend the functionality. Keep up the great work! :)

**Comment by YousefED** [comment] 2024-08-26 07:40
Thanks, happy to help @luukbox !

In case your company has any budget for it, consider [sponsoring](https://www.blocknotejs.org/pricing) the project for more features and support :)
