### ISSUE TITLE
Hyperlink toolbar button is not working on Safari.

### ISSUE THREAD

**Issue by hsingh-ds** [TypeCellOS/BlockNote#530] opened 2024-01-18 16:31 UTC
**Describe the bug**
I am trying to create a hyperlink on safari browser but the button is not working.

**To Reproduce**
Open editor app in Safari browser and try to add hyperlink.

**Comment by v-porytskyi** [comment] 2024-01-19 14:42
And I see the same behavior. But the paragraph colors and buttons are also not working in my case.

**Comment by eatmoarrice** [comment] 2024-01-21 03:58
0.10.1 works btw. It breaks on 0.11.0.

**Comment by eatmoarrice** [comment] 2024-01-22 04:25
This seems to be fixed in 0.11.1.

**Comment by artwist-polyakov** [comment] 2024-02-12 14:30
Hello, can you tell me why you are closing this Issue? After all, the bug persists in safari until now.

**Comment by YousefED** [comment] 2024-02-13 09:21
> Hello, can you tell me why you are closing this Issue? After all, the bug persists in safari until now.

Hi! Can you confirm you're still having this issue on the latest version? (@eatmoarrice reported it was fixed).

On a side note, we can always prioritize issues for sponsors and / or take contributions, these largely drive our roadmap / prioritization

**Comment by artwist-polyakov** [comment] 2024-02-13 10:14
> Hi @artwist-polyakov ! Can you confirm you're still having this issue on the latest version? (@eatmoarrice reported it was fixed).

Hello,

Yes, I can confirm that I am still experiencing the issue with hyperlinks not working in Safari even after checking the latest version available at [BlockNote.js](https://www.blocknotejs.org). If there has been a more recent update that is not reflected on the website, could you please point me to where I can access it? Otherwise, it seems the problem persists in the version currently provided on the official site.

**Comment by eatmoarrice** [comment] 2024-02-13 16:24
Sorry it is indeed not working. There are several conditions where it works, and my testing happened to be under one such:
- When you interact with the menu that appears after rearranging the blocks.
- When you interact with the menu that appears after a long press on the hyperlink button (the menu will disappear for a sec, then re-appear).
![hyperlink](https://github.com/TypeCellOS/BlockNote/assets/63140320/d57a1626-42b3-4616-a59a-e683cc57c359)

**Comment by artwist-polyakov** [comment] 2024-02-14 16:59
Could we reopen this issue (as not fixed)?

**Closed** 2024-03-05 13:48 UTC
Labels: bug, prio:mid
