### ISSUE TITLE
The hint text is not hidden during collaboration

### ISSUE THREAD

**Issue by saculNiot** [TypeCellOS/BlockNote#706] opened 2024-04-17 15:37 UTC
**Describe the bug**
I am using the Tiptap Collaboration
When I move the cursor on the a list item in browser A, the hint text (List) is not hidden on the item list in the browser B. Thi sis shown in the figure below with the red line underneath.
![image](https://github.com/TypeCellOS/BlockNote/assets/44521432/1e42b3a8-7a40-4289-8b4a-210e26202208)

**To Reproduce**
When I move the cursor on the a list item in browser A, the hint text (List) is not hidden on the item list in the browser B. Thi sis shown in the figure below with the red line underneath.

**Misc**
- Node version: v18.20.1
- Package manager: Yarn 
- Browser: Google Chrome

**Comment by YousefED** [comment] 2024-05-01 11:37
duplicate of https://github.com/TypeCellOS/BlockNote/issues/702

**Closed by YousefED** 2024-05-01 11:37 UTC
Labels: bug
